app = "hajime-app"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "sh -c 'cd /app/server && npx knex migrate:latest'"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.headers]
    Cache-Control = "public, max-age=0, must-revalidate"

[[http_service.headers.for_single_file]]
  filename = "index.html"
  Cache-Control = "public, max-age=0, no-cache, no-store, must-revalidate"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
