export type LicenseeApplicationFormData = {
  businessName: string;
  affiliatedGroup: string;
  licenseeNum: string;
  hstNum: string;
  shippingAddr: string;
  city: string;
  province: string;
  postalCode: string;
  phone: string;
  contactName: string;
  contactTitle: string;
  contactPhone: string;
  contactEmail: string;
  acctName: string;
  acctTitle: string;
  acctPhone: string;
  acctEmail: string;
  paymentMethod: "Credit Card" | "EFT" | "E-Transfer" | "Cheque";
  cardExpiry: string;
  cardInitial: string;
  billingSame: boolean;
  billingAddr: string;
  billingCity: string;
  billingPostal: string;
  billingPhone: string;
  frontDoor: boolean;
  loadingDock: boolean;
  poRequired: boolean;
  signatureRequired: boolean;
  operatingDays: string;
  receivingHours: string;
  receiverName: string;
  receiverPhone: string;
  doorCode: string;
  deliveryNotes: string;
  printName: string;
  signature: string;
  date: string;
  agreed: boolean;
};

export type LicenseeApplicationContext = {
  token: string;
  email: string;
  storeName: string;
  tradingName: string;
  wholesalerName: string;
  salesRepName: string;
  expiresAt: string;
  alreadySubmitted: boolean;
  submittedAt: string | null;
  steps: string[];
};
